'use client';

import { useState } from 'react';
import { Plus, Pencil, Trash2, Search, Eye, FileText } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { useApi, useMutation } from '@/lib/hooks';
import { Modal, PageHeader } from '@/components/ui';

type Post = { _id: string; title: string; slug: string; excerpt: string; content: string; category?: string; tags?: string[]; coverImageUrl?: string; status: 'DRAFT' | 'PUBLISHED'; publishedAt?: string; authorName?: string; createdAt: string };
const empty = { title: '', excerpt: '', content: '', category: '', tags: '', coverImageUrl: '', status: 'DRAFT' };

export default function BlogAdminPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('');
  const [editing, setEditing] = useState<Post | null>(null); const [form, setForm] = useState<any>(empty); const [open, setOpen] = useState(false);
  const { data, isLoading, refetch } = useApi(() => api.blogPosts.list({ limit: 50, ...(search ? { search } : {}), ...(status ? { status } : {}) }), [search, status]);
  const create = useMutation(api.blogPosts.create); const update = useMutation((input: { id: string; data: any }) => api.blogPosts.update(input.id, input.data)); const remove = useMutation(api.blogPosts.delete);
  const posts: Post[] = Array.isArray(data) ? data : (data?.items || []);
  const showForm = (post?: Post) => { setEditing(post || null); setForm(post ? { ...post, tags: (post.tags || []).join(', ') } : empty); setOpen(true); };
  const save = async () => {
    if (!form.title.trim() || !form.excerpt.trim() || !form.content.trim()) return toast.error('Title, excerpt and article content are required');
    const payload = { title: form.title, excerpt: form.excerpt, content: form.content, category: form.category || undefined, coverImageUrl: form.coverImageUrl || undefined, tags: String(form.tags || '').split(',').map((tag: string) => tag.trim()).filter(Boolean), status: form.status };
    const result = editing ? await update.mutate({ id: editing._id, data: payload }) : await create.mutate(payload);
    if (result) { toast.success(editing ? 'Blog post updated' : 'Blog post created'); setOpen(false); refetch(); }
  };
  const deletePost = async (post: Post) => { if (!confirm(`Delete “${post.title}”?`)) return; const result = await remove.mutate(post._id); if (result) { toast.success('Blog post deleted'); refetch(); } };
  return <div className="space-y-6">
    <PageHeader title="Blog" description="Write, publish and manage articles shown on rubyplus.net" actions={<button onClick={() => showForm()} className="btn-primary"><Plus className="h-4 w-4" /> New post</button>} />
    <div className="card p-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-gray-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search posts" className="input pl-10" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="input sm:w-44"><option value="">All statuses</option><option value="DRAFT">Drafts</option><option value="PUBLISHED">Published</option></select></div>
    <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="p-4">Post</th><th className="p-4">Category</th><th className="p-4">Status</th><th className="p-4">Published</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{posts.map(post => <tr key={post._id} className="border-b last:border-0"><td className="p-4"><p className="font-semibold text-gray-900">{post.title}</p><p className="mt-1 max-w-xl truncate text-xs text-gray-500">/blog/{post.slug}</p></td><td className="p-4 text-gray-600">{post.category || '—'}</td><td className="p-4"><span className={post.status === 'PUBLISHED' ? 'badge-success' : 'badge-neutral'}>{post.status}</span></td><td className="p-4 text-gray-600">{post.publishedAt ? new Date(post.publishedAt).toLocaleDateString('en-NG') : '—'}</td><td className="p-4"><div className="flex justify-end gap-2"><a href={`/blog/${post.slug}`} target="_blank" rel="noreferrer" className="icon-button" aria-label="View post"><Eye className="h-4 w-4" /></a><button onClick={() => showForm(post)} className="icon-button"><Pencil className="h-4 w-4" /></button><button onClick={() => deletePost(post)} className="icon-button text-red-500"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>{!isLoading && !posts.length && <div className="p-16 text-center text-gray-500"><FileText className="mx-auto mb-3 h-9 w-9 text-gray-300" />No blog posts yet.</div>}</div>
    <Modal isOpen={open} onClose={() => setOpen(false)} title={editing ? 'Edit blog post' : 'New blog post'} size="xl"><div className="space-y-4"><label className="block text-sm font-medium">Title<input className="input mt-1" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label className="block text-sm font-medium">Excerpt<input className="input mt-1" maxLength={320} value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Category<input className="input mt-1" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} /></label><label className="block text-sm font-medium">Tags <span className="font-normal text-gray-400">(comma-separated)</span><input className="input mt-1" value={form.tags} onChange={e => setForm({ ...form, tags: e.target.value })} /></label></div><label className="block text-sm font-medium">Cover image URL <span className="font-normal text-gray-400">(optional)</span><input className="input mt-1" type="url" value={form.coverImageUrl} onChange={e => setForm({ ...form, coverImageUrl: e.target.value })} /></label><label className="block text-sm font-medium">Article content <span className="font-normal text-gray-400">(plain text / markdown)</span><textarea className="input mt-1 min-h-64 resize-y" value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} /></label><label className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={form.status === 'PUBLISHED'} onChange={e => setForm({ ...form, status: e.target.checked ? 'PUBLISHED' : 'DRAFT' })} /><span><strong>Publish now</strong><small className="block text-gray-500">Published posts are immediately visible on the website.</small></span></label><div className="flex justify-end gap-3"><button className="btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" disabled={create.isLoading || update.isLoading} onClick={save}>{create.isLoading || update.isLoading ? 'Saving…' : editing ? 'Save changes' : 'Create post'}</button></div></div></Modal>
  </div>;
}
