'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Plus, Search, Package, Pencil, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { useDeleteProduct, useProducts, type BusinessProduct } from '@/lib/business-api/products';

export default function ProductsPage() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const { data, isLoading, error, refetch } = useProducts({ limit: 100, status: status || undefined, search: search || undefined });
  const remove = useDeleteProduct(() => { toast.success('Product deleted.'); refetch(); });
  const products = useMemo(() => (data ?? []).filter((product) => product.name.toLowerCase().includes(search.toLowerCase())), [data, search]);
  return <div className="p-6 max-w-7xl mx-auto"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6"><div><p className="text-xs font-semibold uppercase tracking-wider text-ruby-red">Catalogue</p><h1 className="mt-1 text-2xl font-bold text-gray-900">Products</h1><p className="mt-1 text-sm text-gray-500">Manage what customers can order from your business.</p></div><Link href="/business/dashboard/products/create" className="inline-flex items-center justify-center gap-2 rounded-lg bg-ruby-red px-4 py-2.5 text-sm font-semibold text-white hover:opacity-95"><Plus size={17}/> Add product</Link></div><div className="bg-white border border-gray-200 rounded-xl p-3 mb-4 flex flex-col sm:flex-row gap-3"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search products" className="w-full rounded-lg border border-gray-200 py-2 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ruby-red"/></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-gray-200 px-3 py-2 text-sm"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="DRAFT">Draft</option><option value="OUT_OF_STOCK">Out of stock</option><option value="INACTIVE">Inactive</option></select></div>{error ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">{error}</div> : isLoading ? <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{[1,2,3,4,5,6].map((key) => <div key={key} className="skeleton h-52 rounded-xl"/>)}</div> : products.length ? <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{products.map((product) => <ProductCard key={product._id} product={product} onDelete={() => { if (window.confirm(`Delete ${product.name}?`)) remove.mutate(product._id); }}/>)}</div> : <div className="rounded-xl border border-dashed border-gray-300 p-12 text-center"><Package className="mx-auto text-gray-300" size={34}/><h2 className="mt-3 font-semibold text-gray-900">No products yet</h2><p className="mt-1 text-sm text-gray-500">Add your first item to begin receiving orders.</p></div>}</div>;
}
function ProductCard({ product, onDelete }: { product: BusinessProduct; onDelete: () => void }) { const image = product.images?.find((item) => item.isPrimary)?.url ?? product.images?.[0]?.url ?? product.media?.[0]?.url; const price = product.basePrice ?? product.price ?? 0; return <article className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="h-32 bg-gray-100">{image ? <img src={image} alt="" className="h-full w-full object-cover"/> : <div className="h-full flex items-center justify-center text-gray-300"><Package size={28}/></div>}</div><div className="p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold text-gray-900">{product.name}</h2><p className="mt-1 text-sm font-bold text-gray-900">₦{Math.round(price).toLocaleString('en-NG')}</p></div><span className="h-fit rounded-full bg-gray-100 px-2 py-1 text-[10px] font-semibold text-gray-600">{product.status}</span></div><div className="mt-4 flex gap-2"><Link href={`/business/dashboard/products/${product._id}`} className="flex-1 inline-flex items-center justify-center gap-1 rounded-lg border border-gray-200 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50"><Pencil size={13}/> Edit</Link><button type="button" onClick={onDelete} className="rounded-lg border border-rose-200 px-3 text-rose-600 hover:bg-rose-50"><Trash2 size={14}/></button></div></div></article>; }
