'use client';

import { FormEvent, useState } from 'react';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { useBusinessAuth } from '@/lib/business-auth';
import { NotificationPreferences } from '@/components/business/settings/NotificationPreferences';
import { BusinessPreviewLink } from '@/components/business/settings/BusinessPreviewLink';
import { BusinessVerification } from '@/components/business/settings/BusinessVerification';

export default function SettingsPage() {
  const { user } = useBusinessAuth();
  const [currentPassword, setCurrent] = useState(''); const [newPassword, setNew] = useState('');
  const [firstName, setFirstName] = useState(user?.firstName ?? ''); const [lastName, setLastName] = useState(user?.lastName ?? ''); const [phone, setPhone] = useState(user?.phone ?? '');
  const [savingProfile, setSavingProfile] = useState(false); const [newEmail, setNewEmail] = useState(''); const [emailOtp, setEmailOtp] = useState(''); const [emailPending, setEmailPending] = useState(false); const [phoneOtp, setPhoneOtp] = useState(''); const [phonePending, setPhonePending] = useState(false);
  const savePassword = async (event: FormEvent) => { event.preventDefault(); try { await api.businessSettings.changePassword({ currentPassword, newPassword }); toast.success('Password updated'); setCurrent(''); setNew(''); } catch {} };
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setSavingProfile(true); try { await api.businessSettings.updateProfile({ firstName, lastName, phone }); toast.success('Profile updated'); } finally { setSavingProfile(false); } };
  const requestEmail = async (event: FormEvent) => { event.preventDefault(); const email = newEmail.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(email) || email === user?.email) return toast.error('Enter a different valid email address'); try { await api.businessSettings.requestEmailChange(email); setEmailPending(true); toast.success('Verification code sent to your new email'); } catch {} };
  const verifyEmail = async (event: FormEvent) => { event.preventDefault(); try { await api.businessSettings.verifyEmailChange(emailOtp.trim()); setEmailPending(false); setEmailOtp(''); setNewEmail(''); toast.success('Email updated — refresh to see it'); } catch {} };
  const requestPhone = async (event: FormEvent) => { event.preventDefault(); try { await api.businessSettings.sendPhoneOtp(phone.trim() || undefined); setPhonePending(true); toast.success('SMS verification code sent'); } catch {} };
  const verifyPhone = async (event: FormEvent) => { event.preventDefault(); try { await api.businessSettings.verifyPhoneOtp(phoneOtp.trim()); setPhoneOtp(''); setPhonePending(false); toast.success('Phone number verified'); } catch {} };
  return <main className="mx-auto max-w-3xl p-6"><h1 className="text-2xl font-bold">Settings</h1><p className="mt-1 text-sm text-gray-500">Manage your account details, login security and business alerts.</p>
    <form onSubmit={saveProfile} className="mt-5 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><div className="md:col-span-2"><h2 className="font-bold">Personal information</h2><p className="mt-1 text-sm text-gray-600">{user?.email}</p></div><input required value={firstName} onChange={(event) => setFirstName(event.target.value)} placeholder="First name" className="rounded-lg border p-3" /><input required value={lastName} onChange={(event) => setLastName(event.target.value)} placeholder="Last name" className="rounded-lg border p-3" /><input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Phone number" className="rounded-lg border p-3 md:col-span-2" /><button disabled={savingProfile} className="w-fit rounded-lg border px-4 py-2.5 text-sm font-semibold disabled:opacity-60">{savingProfile ? 'Saving…' : 'Save profile'}</button></form>
    <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-bold">Email address</h2><p className="mt-1 text-sm text-gray-500">Changing your email requires a code sent to the new address.</p>{!emailPending ? <form onSubmit={requestEmail} className="mt-4 flex flex-col gap-3 sm:flex-row"><input required type="email" value={newEmail} onChange={(event) => setNewEmail(event.target.value)} placeholder="New email address" className="flex-1 rounded-lg border p-3" /><button className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Send code</button></form> : <form onSubmit={verifyEmail} className="mt-4 flex flex-col gap-3 sm:flex-row"><input required inputMode="numeric" maxLength={6} value={emailOtp} onChange={(event) => setEmailOtp(event.target.value.replace(/\D/g, ''))} placeholder="6-digit code" className="flex-1 rounded-lg border p-3" /><button className="rounded-lg bg-ruby-red px-4 py-2.5 text-sm font-semibold text-white">Verify email</button><button type="button" onClick={() => void api.businessSettings.resendEmailChange()} className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Resend</button><button type="button" onClick={() => { void api.businessSettings.cancelEmailChange(); setEmailPending(false); }} className="text-sm text-gray-500">Cancel</button></form>}</section>
    <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-bold">Phone verification</h2><p className="mt-1 text-sm text-gray-500">{user?.isPhoneVerified ? 'Your current number is verified.' : 'Verify your number to secure account recovery and SMS alerts.'}</p>{!phonePending ? <form onSubmit={requestPhone} className="mt-4"><button className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Send SMS code</button></form> : <form onSubmit={verifyPhone} className="mt-4 flex flex-col gap-3 sm:flex-row"><input required inputMode="numeric" maxLength={6} value={phoneOtp} onChange={(event) => setPhoneOtp(event.target.value.replace(/\D/g, ''))} placeholder="6-digit SMS code" className="flex-1 rounded-lg border p-3" /><button className="rounded-lg bg-ruby-red px-4 py-2.5 text-sm font-semibold text-white">Verify phone</button></form>}</section>
    <form onSubmit={savePassword} className="mt-5 space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">Change password</h2><p className="text-sm text-gray-500">Use at least 8 characters with upper and lower case letters, a number and a symbol.</p><input required type="password" value={currentPassword} onChange={(event) => setCurrent(event.target.value)} placeholder="Current password" className="w-full rounded-lg border p-3" /><input required minLength={8} type="password" value={newPassword} onChange={(event) => setNew(event.target.value)} placeholder="New password" className="w-full rounded-lg border p-3" /><button className="rounded-lg bg-ruby-red px-4 py-2.5 text-sm font-semibold text-white">Update password</button></form>
    <BusinessPreviewLink /><NotificationPreferences /><BusinessVerification />
    <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-bold">Legal & about</h2><p className="mt-1 text-sm text-gray-500">Read the policies and platform information that apply to your Ruby+ Business account.</p><div className="mt-4 flex flex-wrap gap-3"><a href="/terms" target="_blank" rel="noreferrer" className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Terms of service</a><a href="/privacy" target="_blank" rel="noreferrer" className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Privacy policy</a><a href="/about" target="_blank" rel="noreferrer" className="rounded-lg border px-4 py-2.5 text-sm font-semibold">About Ruby+</a></div></section>
  </main>;
}
