'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { ArrowLeft, Save } from 'lucide-react';
import { ImageUpload } from '@/components/ui/image-upload';
import { useBusinessAuth } from '@/lib/business-auth';
import { useCreateService, useServiceDetail, useUpdateService, type FulfillmentMode, type PricingType } from '@/lib/business-api/services';
import { AvailabilitySlotBuilder, type AvailabilitySlot } from './AvailabilitySlotBuilder';
import { TemplateFields } from './TemplateFields';

export function ServiceEditor() {
  const { id } = useParams<{ id?: string }>(); const router = useRouter(); const { business } = useBusinessAuth(); const detail = useServiceDetail(id ?? '');
  const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [price,setPrice]=useState(''); const [duration,setDuration]=useState('60'); const [pricing,setPricing]=useState<PricingType>('FIXED'); const [fulfillment,setFulfillment]=useState<FulfillmentMode>('ON_SITE'); const [image,setImage]=useState<string>(); const [availability,setAvailability]=useState<AvailabilitySlot[]>([]); const [templateData,setTemplateData]=useState<Record<string,string>>({});
  useEffect(()=>{const s=detail.data;if(!s)return;setName(s.name);setDescription(s.description??'');setPrice(String(s.pricing.basePrice));setDuration(String(s.duration.minutes));setPricing(s.pricing.type);setFulfillment(s.fulfillmentMode);setImage(s.coverImageUrl??s.media?.[0]?.url);setAvailability((s.availability??[]) as AvailabilitySlot[]);setTemplateData((s.templateData??{}) as Record<string,string>)},[detail.data]);
  const done=()=>{toast.success(id?'Service updated.':'Service created.');router.push('/business/dashboard/services')}; const create=useCreateService(done); const update=useUpdateService(done); const busy=create.isLoading||update.isLoading;
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!business?._id||!name||!price)return toast.error('Name and price are required.');const data={businessId:business._id,locationId:(business as any).locationId??'',categoryId:(business as any).categoryId??'',name,description:description||undefined,pricing:{type:pricing,basePrice:Number(price)},duration:{minutes:Number(duration)},fulfillmentMode:fulfillment,coverImageUrl:image,media:image?[{url:image,type:'IMAGE' as const,order:0}]:undefined,availability:availability.length?availability:undefined,templateData:Object.keys(templateData).length?templateData:undefined};id?update.mutate({id,data}):create.mutate(data)};
  return <div className="p-6 max-w-3xl mx-auto"><button type="button" onClick={()=>router.back()} className="mb-4 inline-flex gap-1 text-sm text-gray-500"><ArrowLeft size={15}/>Back to services</button><h1 className="text-2xl font-bold">{id?'Edit service':'Add service'}</h1><form onSubmit={submit} className="mt-5 space-y-4"><section className="rounded-xl border p-5 grid sm:grid-cols-2 gap-4"><div className="sm:col-span-2"><ImageUpload value={image} onChange={setImage} folder="services" label="Cover image"/></div><label className="text-sm font-medium">Service name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border p-2.5"/></label><label className="text-sm font-medium">Pricing<select value={pricing} onChange={e=>setPricing(e.target.value as PricingType)} className="mt-1 w-full rounded border p-2.5"><option value="FIXED">Fixed</option><option value="STARTS_FROM">Starts from</option><option value="QUOTE_REQUIRED">Quote required</option></select></label><label className="text-sm font-medium">Price<input required type="number" value={price} onChange={e=>setPrice(e.target.value)} className="mt-1 w-full rounded border p-2.5"/></label><label className="text-sm font-medium">Duration (minutes)<input type="number" value={duration} onChange={e=>setDuration(e.target.value)} className="mt-1 w-full rounded border p-2.5"/></label><label className="text-sm font-medium">Fulfilment<select value={fulfillment} onChange={e=>setFulfillment(e.target.value as FulfillmentMode)} className="mt-1 w-full rounded border p-2.5"><option value="ON_SITE">At business</option><option value="AT_HOME">At customer</option><option value="BOTH">Both</option></select></label><label className="sm:col-span-2 text-sm font-medium">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} className="mt-1 w-full rounded border p-2.5"/></label></section><section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Availability</h2><AvailabilitySlotBuilder value={availability} onChange={setAvailability}/></section><section className="rounded-xl border p-5"><h2 className="mb-3 font-semibold">Custom details</h2><TemplateFields value={templateData} onChange={setTemplateData}/></section><button disabled={busy} className="inline-flex gap-2 rounded bg-ruby-red px-4 py-2.5 text-sm font-semibold text-white"><Save size={16}/>{busy?'Saving…':id?'Save changes':'Create service'}</button></form></div>;
}
