import Link from 'next/link';
import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';

type Post = { _id: string; title: string; slug: string; excerpt: string; category?: string; coverImageUrl?: string; publishedAt?: string; authorName?: string };
const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api';
async function getPosts(): Promise<Post[]> { try { const response = await fetch(`${apiUrl}/public/blog-posts?limit=24`, { next: { revalidate: 60 } }); if (!response.ok) return []; const json = await response.json(); const data = json.data || json; return Array.isArray(data) ? data : data.items || []; } catch { return []; } }
export const metadata = { title: 'Ruby+ Blog | Stories, guides and Nigeria updates', description: 'Stories and practical guides from Ruby+.' };

export default async function BlogPage() { const posts = await getPosts(); return <><Navbar /><main className="min-h-screen bg-gray-50 pt-16"><section className="bg-gradient-to-br from-[#1f0a15] via-[#6d1524] to-ruby-red px-5 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.24em] text-white/70">Ruby+ journal</p><h1 className="max-w-3xl text-4xl font-bold leading-tight md:text-6xl">Stories that bring you closer to Nigeria.</h1><p className="mt-5 max-w-2xl text-base text-white/80 md:text-lg">Guides, local discoveries and ideas from the Ruby+ community.</p></div></section><section className="mx-auto max-w-6xl px-5 py-12">{posts.length ? <div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{posts.map(post => <article key={post._id} className="group overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">{post.coverImageUrl ? <div className="aspect-[16/9] overflow-hidden"><img src={post.coverImageUrl} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div> : <div className="flex aspect-[16/9] items-center justify-center bg-gradient-to-br from-ruby-red/15 to-rose-100 text-4xl">♦</div>}<div className="p-6">{post.category && <p className="mb-3 text-xs font-bold uppercase tracking-wider text-ruby-red">{post.category}</p>}<h2 className="text-xl font-bold leading-snug text-gray-900">{post.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-gray-600">{post.excerpt}</p><div className="mt-5 flex items-center justify-between text-xs text-gray-500"><span>{post.publishedAt ? new Date(post.publishedAt).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' }) : ''}</span><Link href={`/blog/${post.slug}`} className="font-semibold text-ruby-red">Read article →</Link></div></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-gray-300 bg-white px-6 py-20 text-center"><h2 className="text-xl font-bold text-gray-900">Stories are coming soon.</h2><p className="mt-2 text-gray-600">Check back for Ruby+ guides, updates and local discoveries.</p></div>}</section></main><Footer /></>; }
