'use client';
import { useCallback } from 'react'; import { api } from '@/lib/api'; import { useMutation } from '@/lib/hooks'; import { useBusinessAuth } from '@/lib/business-auth'; import { useBusinessQuery } from './hooks';
export type PricingType='FIXED'|'STARTS_FROM'|'QUOTE_REQUIRED'; export type FulfillmentMode='ON_SITE'|'AT_HOME'|'BOTH'; export type ServiceStatus='ACTIVE'|'DRAFT'|'INACTIVE'|'ARCHIVED';
export interface BusinessService { _id:string; businessId:string; name:string; description?:string; category?:string; pricing:{type:PricingType;basePrice:number;depositPercent?:number}; duration:{minutes:number;isFlexible?:boolean;minMinutes?:number;maxMinutes?:number}; fulfillmentMode:FulfillmentMode; status:ServiceStatus; isActive:boolean; media?:Array<{url:string;type:'IMAGE'|'VIDEO';caption?:string;order?:number}>; coverImageUrl?:string; availability?:unknown[]; cancellationPolicy?:{freeCancellationHours?:number;cancellationFeePercent?:number}; requirements?:string[]; includes?:string[]; excludes?:string[]; templateData?:Record<string,unknown>; price?:number; pricingType?:PricingType; durationMinutes?:number; createdAt:string; }
export interface CreateServicePayload { businessId:string; locationId:string; categoryId:string; subcategoryId?:string; name:string; description?:string; category?:string; pricing:BusinessService['pricing']; duration:BusinessService['duration']; fulfillmentMode:FulfillmentMode; media?:BusinessService['media']; coverImageUrl?:string; availability?:unknown[]; cancellationPolicy?:BusinessService['cancellationPolicy']; requirements?:string[]; includes?:string[]; excludes?:string[]; templateData?:Record<string,unknown>; }
export type UpdateServicePayload=Partial<CreateServicePayload>;
export function useServices(status?:string) { const {business}=useBusinessAuth(); const id=business?._id??''; const f=useCallback(()=>api.businessServices.list(id,status),[id,status]); return useBusinessQuery(f,[id,status],{enabled:!!id}); }
export function useServiceDetail(id:string) { const f=useCallback(()=>api.businessServices.detail(id),[id]); return useBusinessQuery(f,[id],{enabled:!!id}); }
export function useCreateService(onSuccess?:()=>void) { return useMutation<BusinessService,CreateServicePayload>((data)=>api.businessServices.create(data),{onSuccess}); }
export function useUpdateService(onSuccess?:()=>void) { return useMutation<BusinessService,{id:string;data:UpdateServicePayload}>(({id,data})=>api.businessServices.update(id,data),{onSuccess}); }
export function useDeleteService(onSuccess?:()=>void) { return useMutation<void,string>((id)=>api.businessServices.remove(id),{onSuccess}); }
export function useToggleServiceStatus(onSuccess?:()=>void) { return useMutation<BusinessService,{id:string;isActive:boolean}>(({id,isActive})=>isActive?api.businessServices.activate(id):api.businessServices.deactivate(id),{onSuccess}); }
